# numpy are array having same type of elements it is compact than list  it is fast due to written in c


In [3]:
import numpy as np
import math as m

In [18]:
#how to craete numpy array
l=[1,2,3]
a=np.array(l)
print(l)
print(a)
print(type(l))
print(type(a))

##############################find datay type of a numpy array elements
print(a.dtype)

b=[1,2,3,"5"]
b2=np.array(b)
print(b2)  ## it converts ALL elements into str


#######################################some 1d array functions
a1=np.ones(10)
print(a1)
a0=np.zeros(10)
print(a0)
print(a0.dtype)

a0_int=np.zeros(10,int)
print(a0_int)
print(a0_int.dtype)

[1, 2, 3]
[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>
int32
['1' '2' '3' '5']
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[0 0 0 0 0 0 0 0 0 0]
int32


In [6]:
########## create 2d matrix

a2d=np.zeros((2,3),int)
print(a2d)


a2d[0][1]="2"
print(a2d)  #############################automatically convert "1" to int 1

###### multidimnsional
amd=np.zeros((2,4,2),int)


print(amd.size)    ########### .size tells total no. of element


amd

[[0 0 0]
 [0 0 0]]
[[0 2 0]
 [0 0 0]]
16


array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [35]:
############## slicing works in this too


##############size or shape of numpy
print(a2d.shape)

(2, 3)


In [18]:
##acessing elements
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,7]])
print(arr)
print()

print(arr[0])  #this gives first row
print()
print(arr[:,0])  ## this gives first column  means "[:"-> acces all row but just first column
print()
print(arr[0:2,0])  ## this means first column but from row 1 and 1
print()
print(arr[:,0:2])  ## this gives all rows from column 0 to 1
print()
print(arr[0,0:2])  ## this means first row but just columnt 0 to 1
print()
print(arr[:,0:2].shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11  7]]

[1 2 3]

[ 1  4  7 10]

[1 4]

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]

[1 2]

(4, 2)


# numpy operations  --->

In [69]:
###it works as elemenst wise
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+2)  ## it just adds 2 in each elements
print(a+b)  ## it just adda a and b elments wise if dimenssions are not same than we get error

print(a*2)
print(a*b)

[3 4 5]
[5 7 9]
[2 4 6]
[ 4 10 18]


In [71]:
print(a.sum())
print(a.mean())

6
2.0


In [76]:
#### find square distance
a=np.array([1,2,3])
b=np.array([4,5,6])
sq_d=((a-b)**2).sum()
m.sqrt(sq_d)

5.196152422706632

In [80]:
## calculate standard deviation sigma(x-xbar)**2
a=np.array([1,2,3])
print(a)
std=((a-a.mean())**2).sum()
print(std)

[1 2 3]
2.0


In [83]:
a1=np.array([[1,3,5],[45,7,6],[2,4,5]])
a2=np.array([[2,4,6],[3,6,5],[4,6,7]])
a1.dot(a2)

array([[ 31,  52,  56],
       [135, 258, 347],
       [ 36,  62,  67]])

In [33]:
a=np.array([0,1,2,3])
b=np.array([2,3,4,5])
a.dot(b)


print(np.sum([[0, 1], [0, 5]] , axis=1))    ###### axis 0 for column wise 1 for row wise

[1 5]


In [10]:
#### for creating a array of same interval
x=np.arange(1,5,0.2)
print(x)

y=np.linspace(1,5,10)     ################### this means to generate 10 linearly seperated number bw 1 to 5 
print(y)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [27]:
a=np.array([[1,2,3],[4,6,7]])
a.shape
print(a)
print()


print(a.reshape(3,2))    ############## reshape is use to reshape it in its compitable size
print()
print(a.ravel())    ####### it creates whole array into 1d

[[1 2 3]
 [4 6 7]]

[[1 2]
 [3 4]
 [6 7]]

[1 2 3 4 6 7]
